services:
  - type: web
    name: rag-backend
    env: docker
    dockerfilePath: docker/Dockerfile.backend
    plan: free
    healthCheckPath: /health
    envVars:
      # Secrets (Render will prompt you for these in the dashboard)
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DB_URL
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      # Public variables
      - key: LANGSMITH_PROJECT
        value: rag-business-assistant
      - key: LANGSMITH_TRACING
        value: "true"

  - type: web
    name: rag-frontend
    env: docker
    dockerfilePath: docker/Dockerfile.frontend
    plan: free
    healthCheckPath: /health
    envVars:
      # Render provides an internal network, so the frontend can hit the backend directly!
      - key: BACKEND_URL
        value: http://rag-backend:8000
